baseURL = "/"
languageCode = "en"
title = "Alejandro Henao"
theme = "hugo-initio"

[params]
    name = "Alejandro Henao"
    description = "Data Scientist and MLOps Engineer"
    email = "alejandrohenao91@gmail.com"
    phone = "+57 318 7970321"
    address = "Medellín, Colombia"
    year = 2023
    avatar = "images/picture1.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/picture2.jpeg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    author = "Alejandro Henao"

    showSubheader = true
    showServices = false
    showRecentWorks = true
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "twitter"
	url = "https://twitter.com/alejohenao98"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/alejandro-henao-zapata-95855511a/"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/alejohz"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:alejandrohenao91@gmail.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
